import os

from flask_appbuilder.security.manager import AUTH_DB,AUTH_LDAP
from airflow.configuration import conf


basedir = os.path.abspath(os.path.dirname(__file__))

SQLALCHEMY_DATABASE_URI = conf.get('core', 'SQL_ALCHEMY_CONN')
CSRF_ENABLED = True
AUTH_ROLE_ADMIN = 'Admin'
AUTH_ROLE_PUBLIC = 'Public'
AUTH_USER_REGISTRATION = True
AUTH_USER_REGISTRATION_ROLE = "Viewer"
AUTH_TYPE = AUTH_LDAP
AUTH_LDAP_SERVER = os.getenv("AIRFLOW__LDAP__URI")
AUTH_LDAP_USE_TLS = str(os.getenv("AIRFLOW__LDAP__USE_TLS")).lower() == "true"
AUTH_LDAP_SEARCH = os.getenv("AIRFLOW__LDAP__BASEDN")
AUTH_LDAP_BIND_USER = os.getenv("AIRFLOW__LDAP__BIND_USER")
AUTH_LDAP_BIND_PASSWORD = os.getenv("AIRFLOW__LDAP__BIND_PASSWORD")
AUTH_LDAP_UID_FIELD = os.getenv("AIRFLOW__LDAP__USER_NAME_ATTR")
AUTH_LDAP_FIRSTNAME_FIELD = os.getenv("AIRFLOW__LDAP__FIRSTNAME_FIELD")
AUTH_LDAP_LASTTNAME_FIELD = os.getenv("AIRFLOW__LDAP__LASTTNAME_FIELD")
AUTH_LDAP_EMAIL_FIELD = os.getenv("AIRFLOW__LDAP__EMAIL_FIELD")
APP_THEME = os.getenv("AIRFLOW__WEBSERVER__APP_THEME")
